create table "APP".PRODUTO
(
	CODBARRA VARCHAR(30) default '0' not null primary key,
	NOME VARCHAR(20),
	DESCRICAO VARCHAR(500),
	GENERO VARCHAR(20),
	FAIXAETARIA VARCHAR(20),
	PLATAFORMA VARCHAR(20),
	FABRICANTE VARCHAR(20),
	MARCA VARCHAR(30),
	GARANTIA VARCHAR(30),
	ARMAZENAMENTO VARCHAR(20),
	VALOR DOUBLE,
	TIPO VARCHAR(20),
	QUANTIDADEMINIMA INTEGER default 0,
	QUANTIDADEMAXIMA INTEGER,
	QUANTIDADEATUAL INTEGER,
	STATUS SMALLINT
	
)
create table "APP".USUARIO
(
	EMAIL VARCHAR(100) not null primary key,
	SENHA VARCHAR(100),
	NOMECOMPLETO VARCHAR(100),
	RG VARCHAR(100),
	FILIAL VARCHAR(100),
	CARGO VARCHAR(100),
	TIPOUSUARIO VARCHAR(100),
	ATIVO SMALLINT default 1
)

create table "APP".RELATORIO
(
	DATA VARCHAR(120),
	NOMEDOUSUARIO VARCHAR(120),
	EMAILDOUSUARIO VARCHAR(120),
	FILIAL VARCHAR(120),
	CODIGOPRODUTO VARCHAR(120),
	NOMEDOPRODUTO VARCHAR(120),
	QUANTIDADE INTEGER,
	ACAO VARCHAR(15)
	
)
INSERT INTO USUARIO (EMAIL, SENHA,NOMECOMPLETO, RG, FILIAL, CARGO, TIPOUSUARIO,ATIVO) VALUES ('Admin@Admin.com', '1234', 'Fulano', '354405404', 'SÃO PAULO', 'Gerente','ADMIN' ,1)